language: ruby
cache: bundler
rvm:
  - 2.2.3
sudo: false
bundler_args: --without development
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
script:
  - xvfb-run bundle exec rspec
